#!/bin/bash
mameroot=${MAMEROOT:-"$HOME/.mame"}
if [ ! "$1" ]; then
    echo "Usage: `basename "$0"` game [tag ...]
MAME root directory: $mameroot" 1>&2
    exit 1
fi
game="$1"
shift
nv="$mameroot/nvram/$game.nv"
inp="$mameroot/inp/$game"
snap="$mameroot/snap"
meta="$mameroot/meta.$game"
if [ $# = 0 ]; then
    cd "$meta" &>/dev/null
    echo 'Choose an input file to delete:'
    ls
    read -ep '> ' name
    [ "$name" ] && rm -v "$inp.$name.inp" "$nv.$name" "$meta/$name"
else
    for name in "$@"; do
        rm -v "$inp.$name.inp" "$nv.$name" "$meta/$name"
    done
fi
